spring:
  profiles:
    active: dev
  application:
    name: web-app
  main:
    #解决Bean重复定义问题，dubbo版本和springboot版本问题
    allow-bean-definition-overriding: true
  # 解决 NoHandlerFoundException 捕获不到问题
  mvc:
   throw-exception-if-no-handler-found: true
   static-path-pattern: /statics/**

server:
  #服务端口
  port: 8080

# dubbo配置
dubbo:
  application:
    #rpc服务名
    name: web-app
    #禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    #配置注册中心
    address: nacos://192.168.134.100:8848
  consumer:
    #设置超时时间
    timeout: 3000
    check: false
    retries: 0
